name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - uses: actions/cache@v
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python build_readme.py
        cat README.md
        echo "update complete."
    - name: Update time.md with current timestamp
      run: |-
        date +"%Y-%m-%d %H:%M:%S" > time.md
        cat time.md
        echo "Time updated."
    - name: Commit and push if changed
      run: |-
        git diff
        git config user.email "${{ secrets.COMMIT_EMAIL }}"
        git config user.name "gorpeln"
        git add -A
        git commit -m "Updated content and timestamp" || exit 0
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
